/* gamedata-forge.mjs — Forge (W1) tables, extracted verbatim from N.js.
 * GENERATED by a one-off extraction script (scratchpad, not committed); refresh after a major
 * patch. UNLIKE the other W1 gamedata files, the forge upgrade NAMES/descriptions are NOT a
 * literal N.js table — IdleonToolbox's forge.ts hardcodes them (`upgradesData`), and no matching
 * string table was found in N.js for this pass (the game may render these purely from a
 * different localization table not chased down here). The 6 rows below use toolbox's names as
 * labels; every NUMBER (effect formula, cost formula, costMulti) is independently verified
 * against N.js and matches toolbox's costMulti constants exactly.
 *
 * FURNACE_UPGRADES  6 rows, index = FurnaceLevels[index] save-array slot.
 *   effect formula   — x._customBlock_ForgeStats(d) dispatcher (N.js:5493):
 *     d=0 (New Forge Slot):        FurnaceLevels[0]                                   // raw slot count
 *     d=1 (Ore Capacity Boost):    Math.min(2e9, Holes("CosmoBonusQTY",2,1)
 *                                    * (20 + ArbitraryCode5Inputs("add",10,10,Math.round(FurnaceLevels[1]),0,0))
 *                                    * (1 + (ArcadeBonus(26) + 30*CardLv("Godshard"))/100)
 *                                    * (1 + StampBonusOfTypeX("ForgeCap")/100)
 *                                    * (1 + (GetBribeBonus("35") + Summoning("VaultUpgBonus",26,0))/100)
 *                                    * (1 + (50*AchieveStatus(281) + 25*RiftStuff("RiftSkillBonus,1",1))/100))
 *                                  // client computes this expression twice via a "> 2e9 ? 2e9 : sameExpr"
 *                                  // ternary rather than Math.min — mathematically identical, noted verbatim.
 *     d=2 (Forge Speed):           100 + (5*FurnaceLevels[2] + 30*CardLv("Godshard"))    // % of base speed
 *     d=3 (Forge EXP Gain):        FurnaceLevels[3]                                    // raw, consumed elsewhere as a %
 *     d=4 (Bar Bonanza):           FurnaceLevels[4]                                    // raw, consumed elsewhere as a %
 *     d=5 (Puff Puff Go):          2 * FurnaceLevels[5]
 *   cost formula      — x._customBlock_ForgeUpdateCosts(d) (N.js:5498). NOTE the function's
 *     first statement is `DNSM.ForgeCostReduxALL = 1` — it resets the reduction multiplier to 1
 *     immediately before reading that SAME value back out a few lines later, so
 *     `ForgeCostReduxALL` is always exactly 1 within this call; any external cost-reduction
 *     source for forge upgrades (if one exists) is NOT actually live in this formula as written
 *     — transcribed verbatim rather than "corrected", since that's what N.js does today.
 *     d=0: cost = Math.round(200 * Math.pow(5.4,  Math.pow(FurnaceLevels[0], 0.83)) * ForgeCostReduxALL);
 *     d=1..5:
 *       level = FurnaceLevels[d];
 *       if (level < 5) cost = Math.round(50 * Math.pow(2.5, Math.pow(level, 0.51)) * ForgeCostReduxALL);
 *       else            cost = Math.round(400 * Math.pow(costMulti[d], level - 5) * ForgeCostReduxALL);
 *     d>5: cost = 9999999
 *   `costMulti` per upgrade (d=1..5, verified against N.js literals 1.41/1.2/1.21/1.25/1.33 —
 *   matches IdleonToolbox's forge.ts `upgradesData[].costMulti` exactly) is stored per row below.
 *   `maxLevel` values are carried over from IdleonToolbox's forge.ts (16, 50, 90, 85, 75, 60) —
 *   NOT independently re-derived from an N.js cap check in this pass; flagged as toolbox-sourced.
 */

export const FURNACE_UPGRADES = [
  {"index":0,"name":"New_Forge_Slot","effect":"+1 forge slot per level","costMulti":null,"maxLevel":16},
  {"index":1,"name":"Ore_Capacity_Boost","effect":"increases max ores per slot","costMulti":1.41,"maxLevel":50},
  {"index":2,"name":"Forge_Speed","effect":"ores turned into bars faster","costMulti":1.2,"maxLevel":90},
  {"index":3,"name":"Forge_EXP_Gain","effect":"increased EXP gain from using the forge","costMulti":1.21,"maxLevel":85},
  {"index":4,"name":"Bar_Bonanza","effect":"increased chance to make an extra bar","costMulti":1.25,"maxLevel":75},
  {"index":5,"name":"Puff_Puff_Go","effect":"increased chance for a card drop while afk","costMulti":1.33,"maxLevel":60}
];
