/* gamedata-anvil.mjs — Anvil (W1) tables, extracted verbatim from N.js.
 * GENERATED by a one-off extraction script (scratchpad, not committed); refresh after a major
 * patch. Both tables spot-checked against IdleonToolbox's data/website-data.json
 * (`anvilProducts`, `anvilUpgradeCost`) and matched exactly, 0 mismatches.
 *
 * ANVIL_PRODUCTION   ka.AnvilProductionInfo() (N.js:23343) — 14 rows, columns [rawName,
 *                    requiredAmount, levelReq, exp]. `AnvilPA[index]` on the save is
 *                    [currentAmount, currentXP, currentProgress, totalProduced] per slot;
 *                    `AnvilPAselect` holds which slot(s) each of the account's "hammers" is
 *                    assigned to. levelReq=999 for the last 3 rows (CraftMat15/16/17) — these
 *                    are locked behind something other than a simple smithing-level gate (not
 *                    chased down in this pass; toolbox doesn't resolve it either).
 *
 * ANVIL_UPGRADE_COST 26 rows, NOT a literal N.js array — reconstructed from the nested ternary
 *                    chain behind the `"TypeAnvilPA"==d` dispatcher branch (N.js:5394), which
 *                    picks the material required to raise the "pointsFromMats" cap based on how
 *                    many mat-points have already been spent (AnvilPAstats[2]):
 *                      5>pts ? "Grasslands1" : 15>pts ? "Grasslands2" : 25>pts ? "Grasslands3"
 *                      : 40>pts ? "Jungle1" : 55>pts ? "Jungle3" : 70>pts ? "Forest1"
 *                      : 85>pts ? "Forest3" : 100>pts ? "DesertA1" : 115>pts ? "DesertA3"
 *                      : 130>pts ? "DesertB1" : 150>pts ? "DesertB3" : 175>pts ? "DesertC1"
 *                      : 200>pts ? "DesertC2" : 225>pts ? "DesertC4" : 250>pts ? "SnowA2"
 *                      : 280>pts ? "SnowB1" : 310>pts ? "SnowB3" : 350>pts ? "SnowC1"
 *                      : 375>pts ? "SnowA4" : 410>pts ? "GalaxyA1" : 440>pts ? "GalaxyA3"
 *                      : 470>pts ? "GalaxyA4" : 500>pts ? "GalaxyB1" : 540>pts ? "GalaxyB3"
 *                      : 600>pts ? "GalaxyC1" : "GalaxyC4"
 *                    `costThreshold` below is the number on the LEFT of each `>` comparison
 *                    (the row is active while pointsFromMats is strictly below it); the final
 *                    row (GalaxyC4) has no upper bound (costThreshold: null = "else").
 *
 * ANVIL POINT POOLS — AnvilPAstats save array = [availablePoints, pointsFromCoins, pointsFromMats,
 * xpPoints, speedPoints, capPoints] (6 slots; toolbox's getPlayerAnvil() reads them in this exact
 * order). `pointsFromAcme` is a 7th, non-purchased pool granted by the ACME_ANVIL talent
 * (SkillLevels[281] + talentBonus*floor(smithingLevel/10)) — not part of AnvilPAstats itself.
 * Dispatchers x._customBlock_AnvilProduceStats (N.js:7076) and x._customBlock_ForgeUpdateCosts-
 * style pattern for anvil is x._customBlock_AnvilProduceStats itself covering both stats AND
 * costs for points 1-2 (coins/mats); points 3-5 (xp/speed/cap) have NO purchase-cost formula —
 * "LvUps"==d returns 1, i.e. 1 available point buys exactly 1 level in those three pools.
 *   "Costs1" (gold cost per pointsFromCoins level):
 *     cost = Math.round((Math.pow(pointsFromCoins, 3) + 50) * (1 + pointsFromCoins/100)
 *          * Math.max(0.1, 1 - AlchBubbles.AnvilProdCost/100));
 *   "Costs2" (material cost per pointsFromMats level, item = ANVIL_UPGRADE_COST lookup above):
 *     cost = Math.round((Math.pow(pointsFromMats + 1, 1.5) + pointsFromMats)
 *          * Math.max(0.1, 1 - AlchBubbles.AnvilProdCost/100));
 *   "ProdExpBonus" (xpPoints -> the anvil's own EXP-gain multiplier, feeds getAnvilExp):
 *     smithingExpMulti = (1 + 3*xpPoints/100) * SkillStats("SmithingEXPmulti");
 *     result = smithingExpMulti < 20 ? smithingExpMulti
 *            : Math.min(20 + 50*((smithingExpMulti-20)/(smithingExpMulti-20+70)), 75);
 *   "ProdSpdBonus" (speedPoints -> anvil production speed multiplier):
 *     ProdSpdBonus = (1 + (StampBonusOfTypeX("AnvilPAspd") + 2*speedPoints)/100)
 *          * (1 + (BoxRewards.ProdSpd + StatueBonusGiven11 + Summoning("VaultUpgBonus",24,0))/100)
 *          * (1 + AlchBubbles.AnvilACTIVE/100)
 *          * ProdSpdBonusFromAGI;                    // agility curve, see below
 *     ProductionSpeed = ProdSpdBonus * (1 + SkillStats("TownProdSpeedPCT")/100);
 *     // ProdSpdBonusFromAGI: same shape as the CritChance AGI curve but a different constant
 *     //   AGI<1000: agiCurve = (Math.pow(AGI+1, 0.37) - 1) / 40
 *     //   AGI>=1000: agiCurve = 0.5*((AGI-1000)/(AGI+2500)) + 0.297
 *     //   return 1 + 2*agiCurve;
 *   "Cap" (capPoints -> max stored production per slot):
 *     cap = Math.round(Math.min(2e9, MaxCapacity("bCraft") * (2 + 0.1*capPoints)));
 * All five formulas above match IdleonToolbox's anvil.ts (getAnvilSpeed / getMonsterMatCost /
 * getCoinCost / getAnvilExp / getPlayerAnvil's `Cap` calc) — full agreement, 0 discrepancies.
 * The overall production/hour for a slot with `hammers` assigned:
 *   perHour = Math.min(ProductionSpeed(seconds/hr basis) * hammers / requiredAmount, cap).
 */

export const ANVIL_PRODUCTION = [{"index":0,"rawName":"CraftMat1","requiredAmount":100,"levelReq":1,"exp":6},{"index":1,"rawName":"CraftMat5","requiredAmount":200,"levelReq":5,"exp":10},{"index":2,"rawName":"CraftMat6","requiredAmount":350,"levelReq":12,"exp":16},{"index":3,"rawName":"CraftMat7","requiredAmount":700,"levelReq":17,"exp":25},{"index":4,"rawName":"CraftMat9","requiredAmount":1200,"levelReq":25,"exp":35},{"index":5,"rawName":"CraftMat8","requiredAmount":2000,"levelReq":30,"exp":50},{"index":6,"rawName":"CraftMat10","requiredAmount":3000,"levelReq":35,"exp":65},{"index":7,"rawName":"CraftMat11","requiredAmount":4000,"levelReq":43,"exp":75},{"index":8,"rawName":"CraftMat12","requiredAmount":6000,"levelReq":50,"exp":90},{"index":9,"rawName":"CraftMat13","requiredAmount":8500,"levelReq":60,"exp":110},{"index":10,"rawName":"CraftMat14","requiredAmount":12000,"levelReq":70,"exp":140},{"index":11,"rawName":"CraftMat15","requiredAmount":120000,"levelReq":999,"exp":1000},{"index":12,"rawName":"CraftMat16","requiredAmount":160000,"levelReq":999,"exp":1300},{"index":13,"rawName":"CraftMat17","requiredAmount":250000,"levelReq":999,"exp":2000}];

export const ANVIL_UPGRADE_COST = [{"index":0,"costThreshold":5,"rawName":"Grasslands1"},{"index":1,"costThreshold":15,"rawName":"Grasslands2"},{"index":2,"costThreshold":25,"rawName":"Grasslands3"},{"index":3,"costThreshold":40,"rawName":"Jungle1"},{"index":4,"costThreshold":55,"rawName":"Jungle3"},{"index":5,"costThreshold":70,"rawName":"Forest1"},{"index":6,"costThreshold":85,"rawName":"Forest3"},{"index":7,"costThreshold":100,"rawName":"DesertA1"},{"index":8,"costThreshold":115,"rawName":"DesertA3"},{"index":9,"costThreshold":130,"rawName":"DesertB1"},{"index":10,"costThreshold":150,"rawName":"DesertB3"},{"index":11,"costThreshold":175,"rawName":"DesertC1"},{"index":12,"costThreshold":200,"rawName":"DesertC2"},{"index":13,"costThreshold":225,"rawName":"DesertC4"},{"index":14,"costThreshold":250,"rawName":"SnowA2"},{"index":15,"costThreshold":280,"rawName":"SnowB1"},{"index":16,"costThreshold":310,"rawName":"SnowB3"},{"index":17,"costThreshold":350,"rawName":"SnowC1"},{"index":18,"costThreshold":375,"rawName":"SnowA4"},{"index":19,"costThreshold":410,"rawName":"GalaxyA1"},{"index":20,"costThreshold":440,"rawName":"GalaxyA3"},{"index":21,"costThreshold":470,"rawName":"GalaxyA4"},{"index":22,"costThreshold":500,"rawName":"GalaxyB1"},{"index":23,"costThreshold":540,"rawName":"GalaxyB3"},{"index":24,"costThreshold":600,"rawName":"GalaxyC1"},{"index":25,"costThreshold":null,"rawName":"GalaxyC4"}];
