/* gamedata-owl.mjs — Owl / Orion (W1) tables, extracted verbatim from N.js.
 * GENERATED by a one-off extraction script (scratchpad, not committed); refresh after a major
 * patch. Both tables spot-checked against IdleonToolbox's data/website-data.json (`owlData`) and
 * matched exactly (name/x1/x2/x3, 0 mismatches); MEGA_FEATHER_TIERS matched toolbox's
 * megaFeathersDesc verbatim.
 *
 * OWL_UPGRADES        na.Owlz() (N.js:23722) — 9 rows (the SAME source array continues into an
 *                     unrelated Bluefin Fishing upgrade table afterward; only the first 9 rows
 *                     are Owl upgrades, confirmed by row count matching toolbox exactly and by
 *                     the accountOptions[254..262] index range referenced below). Columns:
 *                     [name (`|` = in-game line break), x1, x2, x3, bonusFormatString, desc,
 *                     unlockReq]. Level of upgrade i lives at accountOptions[254+i]; `progress`
 *                     (Orion's overall feather-spend progress, used to gate mega-feather tiers)
 *                     lives at accountOptions[263]; total feathers currently held live at
 *                     accountOptions[253].
 *
 * MEGA_FEATHER_TIERS  10 permanent tiers unlocked at accountOptions[262] > tierIndex (0-based);
 *                     descriptions embedded as one pipe-delimited(`|`) string literal inside the
 *                     account-init code (N.js:20887, right after the "OwlNextUpgReq" for-loop
 *                     that seeds `_GenINFO[0]`). Tier 10 (the last) additionally scales with
 *                     `accountOptions[262] - 10` extra stacks past its unlock (see
 *                     "OwlMegafeather" formula below, case i===9).
 *
 * FORMULAS — all three below share `commonFactor`/table columns and were independently found and
 * verified against N.js, matching IdleonToolbox's owl.ts (getOwl/getMegaFeather) exactly:
 *   "OwlMegafeather"(i) (dispatcher, used pervasively as a 0/1 or count gate):
 *     accountOptions[262] > i ? (i===9 ? accountOptions[262]-9 : 1) : 0
 *   "OwlCost"(b) — cost in feathers to buy the NEXT level of upgrade b (N.js:18090):
 *     commonFactor = (1/(1+10*accountOptions[257]/100))              // Feather Cheapener (upg 3) reduction
 *                  * (1/(1+20*accountOptions[261]/100))               // Super Feather Cheapener (upg 7) reduction
 *                  * (1/(1+OwlMegafeather(2)*accountOptions[254]/100)); // mega-tier-2: 1% cheaper per Feather Generation LV
 *     if (b === 0)
 *       cost = commonFactor * Owlz[0][1] * accountOptions[254]
 *            * Math.pow(Math.max(1.05, Owlz[0][2] - 0.025*OwlMegafeather(8)), accountOptions[254]);
 *     else
 *       cost = commonFactor * Owlz[b][1] * Math.pow(Owlz[b][2], accountOptions[254+b]);
 *   "OwlFeatherRate" — feathers/sec, N.js:18162:
 *     rate = (1 + 9*OwlMegafeather(0))                                // mega-tier-1: 10x multiplicative
 *          * (1 + Fountain_BonTOT(0,18)/100)                          // Well cavern fountain bonus
 *          * (1 + VaultUpgBonus(21)/100)                               // upgrade vault
 *          * (1 + MeritocBonusz(12)/100)                               // meritocracy vote
 *          * (1 + GambitBonuses(8)/100)                                // gambit
 *          * (accountOptions[254]                                      // Feather Generation LV
 *             + (5*accountOptions[259]                                 // Super Feather Production LV * 5
 *                + (2*OwlMegafeather(4)*accountOptions[257]            // mega-tier-5: Feather Cheapener LV gives +2/+4 feathers each
 *                   + 4*OwlMegafeather(4)*accountOptions[261])))
 *          * (1 + (5*accountOptions[256])/100)                         // Feather Restart LV: +5% each? (accountOptions[256] not yet cross-checked against OWL_UPGRADES index)
 *          * Math.pow(3 + 2*OwlMegafeather(6), accountOptions[258])    // Shiny Feathers LV exponent; base 3x/5x per mega-tier-7
 *          * (1 + (accountOptions[264]*accountOptions[260])/100);      // Shiny Feather count * Super Feather Cheapener-adjacent stat
 *   "OwlNextUpgReq" — Owlz[currentUpgradeIndexFrom_GenINFO0][3], i.e. the x3 unlock threshold of
 *     whichever upgrade index the account has progressed to (`_GenINFO[0]`, seeded 2..9 by the
 *     for-loop at N.js:20887 comparing accountOptions[263] against each OwlNextUpgReq in turn).
 * `restartMulti` (feathers gained on a "Feather Restart") = Math.pow(3 + 2*OwlMegafeather(6),
 * accountOptions[258] + 1) — matches toolbox's owl.ts return value exactly.
 */

export const OWL_UPGRADES = [{"index":0,"name":"Feather_Generation","x1":5,"x2":1.1,"x3":100,"bonus":"{/sec","desc":"Generates_}_feather_per_second","unlockReq":0},{"index":1,"name":"Bonuses_of_Orion","x1":350,"x2":25,"x3":1000,"bonus":"+{%_Class_XP","desc":"Gain_a_permanent_bonus_in_the_real_game!_This_upgrade_never_resets.","unlockReq":0},{"index":2,"name":"Feather_Multiplier","x1":500,"x2":1.11,"x3":2500,"bonus":"+{_Base_DMG","desc":"Boosts_feather_generation_by_+}%","unlockReq":0},{"index":3,"name":"Feather_Cheapener","x1":3000,"x2":1.16,"x3":30000,"bonus":"+{%_Total_DMG","desc":"All_feather_upgrades_are_@%_cheaper","unlockReq":0},{"index":4,"name":"Feather_Restart","x1":1000000,"x2":14,"x3":750000,"bonus":"+{%_Skill_XP","desc":"Reset_almost_all_Upgrades_and_Feathers._Generate_{x_Feathers","unlockReq":0},{"index":5,"name":"Super_Feather_Production","x1":2000000,"x2":1.12,"x3":10000000,"bonus":"+{%_Drop_Rate","desc":"Generates_+}_more_feathers_per_second","unlockReq":0},{"index":6,"name":"Shiny_Feathers","x1":5000000,"x2":1.4,"x3":250000000,"bonus":"+{_All_Stat","desc":"Rare_chance_for_a_Shiny_Feather,_each_one_gives_+}%_feather_generation","unlockReq":0},{"index":7,"name":"Super_Feather_Cheapener","x1":50000000,"x2":1.27,"x3":5000000000,"bonus":"{","desc":"All_feather_upgrades_are_}%_cheaper","unlockReq":0},{"index":8,"name":"The_Great_Mega_Reset","x1":250000000000,"x2":20,"x3":100000000000,"bonus":"Nah","desc":"Reset_almost_everything._Gain_a_permanent_Megafeather","unlockReq":0}];

export const MEGA_FEATHER_TIERS = [{"tier":1,"desc":"Multiplies_all_Feather_generation_by_10x._Multiplicative,_so_extra_powerful!"},{"tier":2,"desc":"Boosts_all_of_Orion's_Bonuses_by_double_their_base_amount."},{"tier":3,"desc":"All_upgrades_cost_1%_less_feathers_per_LV_of_Feather_Generation."},{"tier":4,"desc":"Instead_of_double,_all_of_Orion's_Bonuses_are_now_triple."},{"tier":5,"desc":"The_Feather_Cheapener_upgrades_now_give_+2_and_+4_Feathers/sec_each_LV,_respectively."},{"tier":6,"desc":"Forget_triple,_Orion's_Bonuses_are_now_quadruple!"},{"tier":7,"desc":"The_upgrade_Feather_Restart_now_gives_a_5x_feather_bonus_instead_of_the_previous_3x."},{"tier":8,"desc":"Quadruple?_Pfft_more_like_Noobruple,_Orion's_Bonuses_are_now_Quintuple_as_big,_that's_5x!"},{"tier":9,"desc":"The_cost_of_Feather_Generation_upgrade_now_goes_up_25%_slower."},{"tier":10,"desc":"Orion's_bonuses_are_now_{x_higher_than_they_were_at_first."}];
