/* savemap/w67.mjs — World 6-7 + endgame save keys.
 * Ground truth: N.js (decompiled client), verified against a real save.
 * Most of these converge on `_customBlock_Sailing("BoatArtiMulti")` — see artifactchance.mjs.
 */
export default {
  Holes: {
    name: "caverns", attr: "Holes", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "World 7 The Caverns: villagers, monuments, buildings, fountain, cosmo, resources.",
    idx: {
      1: "villager levels [Explorer,Engineer,Conjuror,Measurer,Librarian,Elder,?,?] (names: CustomLists.HolesInfo[20])",
      4: "cosmo upgrade levels; CosmoBonusQTY(b,e) reads Holes[4+b][e]",
      9: "cavern resource currencies (38). [9][11] = Natural Notes, feeds B_UPG 55",
      13: "building/upgrade unlock flags (150). B_UPG(b) returns 0 when Holes[13][b]==0",
      14: "Bravery state; [0] feeds Bravery_MinDMG/MaxDMG",
      15: "monument bonus levels, flat index = 10*monument + slot. [15][12] = Monument of Justice artifact-find level; [15][19] = Justice Bonuses Multi",
      16: "feeds B_UPG 45 (sum -> 1.1^floor(sum/25))",
      31: "fountain upgrade levels [waterType][upgIdx]",
      32: "fountain marble ranks [waterType][upgIdx]",
    },
    evidence: "N.js _customBlock_Holes(\"MonumentROGbonuses\",b,e) ~10748038 reads Holes[15][10*b+e] with coeff CustomLists.HolesInfo[37][10*b+e]; HolesInfo[32][12]=\"}x_Artifact|Find_Chance\". _customBlock_Holes(\"B_UPG\",55) ~10731680 reads Holes[9][11]; HolesBuildings[55]=\"Tune_of_Artifaction\".",
    confidence: "confirmed",
  },
  Summon: {
    name: "summoning", attr: "Summon", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Summoning: unit levels and the list of defeated summoning enemies.",
    idx: {
      0: "summoning unit levels",
      1: "defeated summon enemy names. Names starting with 'rift' are EXCLUDED from WinBonus.",
    },
    evidence: "N.js _customBlock_Summoning(\"WinBonus\",..) @10671364 iterates Summon[1], maps name -> CustomLists.SummonEnemies[0].indexOf(name), accumulates SummonEnemies[7][i] into slot SummonEnemies[5][i]-1.",
    confidence: "confirmed",
  },
  UpgVault: {
    name: "vaultUpgrades", attr: "UpgVault", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Summoning Vault upgrade levels. 90 REAL upgrades (CustomLists.UpgradeVault.length===90); the save array is padded to 100 — indices 90-99 are dead.",
    idx: {
      63: "Artifact_Find_Chance (+% per level; UpgradeVault[63][5] coeff = 1)",
      32: "Vault Mastery I (multiplies upgrades b<32)",
      61: "Vault Mastery II (multiplies 32<=b<61)",
      89: "Vault Mastery III (multiplies 61<=b<89; itself exempt)",
    },
    evidence: "N.js _customBlock_Summoning(\"VaultUpgBonus\",b,0) @10637795: level * UpgradeVault[b][5], times a mastery multiplier chosen by band. UpgradeVault[63][0]==\"Artifact_Find_Chance\".",
    confidence: "confirmed",
  },
  Ninja: {
    name: "ninja", attr: "Ninja", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Sneaking/Ninja: 108 entries. Twin state, inventory, equipment, charms, pristine charms. PARTIALLY MAPPED.",
    idx: {
      102: "W6 item currency ([1] used by W6item0)",
      106: "list of item names already obtained (drop dedup)",
      107: "PRISTINE CHARM unlock flags (40). [107][2] = Glowing_Veil (}x Artifact Find Chance); [107][8] = Crystal_Comb (}x Summoning Winner Bonuses)",
    },
    evidence: "N.js _customBlock_Ninja(\"PristineBon\",b,0) @10616776: `return 1==Ninja[107][b] ? CustomMaps.NjEQ[\"NjTrP\"+b][3] : 0`. NjEQ.NjTrP2 = \"3 2 Glowing_Veil 40 ... }x_Artifact_Find_Chance\" (field[3]=40). Set to 1 @11120619 on charm pickup.",
    confidence: "confirmed",
  },
  Spelunk: {
    name: "spelunking", attr: "Spelunk", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Spelunking (Caverns minigame): cave unlocks, depths, POW, shop upgrades, discoveries, lore.",
    idx: {
      0: "cave unlock flags (15)",
      1: "per-cave depth/progress (15)",
      2: "per-cave POW/currency (15)",
      5: "spelunk shop upgrade levels (90)",
      6: "DISCOVERY NAMES — array of discovered rock names (87 of 99 possible). Its LENGTH feeds 1.02^n artifact find, 1.01^n class EXP, 1.05^n collectible, 1.03^n EXP.",
      9: "gaming palette levels (37); [9][5] feeds GamingStatType(\"PaletteBonus\",5,0)",
      46: "equipment hat names",
    },
    evidence: "N.js @12402022 `Spelunk[6].push(CustomLists.SpelunkRocks[cave][rock][0])`; `D.contains(Spelunk[6], name)` is the discovered check @12380018. SpelunkRocks = 9 caves, 99 rocks. GamingUpg[26]=\"1.02x_Artifact_chance_per_Spelunk_Discovery\".",
    confidence: "confirmed",
  },
  Research: {
    name: "research", attr: "Research", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Research (Minehead/grid): grid node levels, occurrence tags, observations, farming stickers.",
    idx: {
      0: "grid node LEVELS (240; parallel to CustomLists.ResGridSquares)",
      1: "grid node OCCURRENCE index (240); -1 = none, else index into CustomLists.Research[5] = [25,15,50,20,20,35,25,30,35,60] (percent)",
      7: "research progress/AFK state",
      9: "FARMING STICKER counts (12; parallel to CustomLists.Research[23] names and [25] coeffs). [9][2] = Chocotastic Muffin Sticker (artifact find).",
      11: "observations list (length feeds Grid_Bonus 67/68/107)",
    },
    evidence: "N.js _customBlock_ResearchStuff(\"Grid_Bonus\",b,0) @10901346: ResGridSquares[b][2] * Research[0][b] * (Research[1][b]==-1 ? 1 : 1+Research[5][Research[1][b]]/100) * max(1, Grid_Bonus_Allmulti). ResGridSquares[109][0]=\"Transcendent_Artifacts\", [106][0]=\"The_Maw\".",
    confidence: "confirmed",
  },
  Sushi: {
    name: "sushi", attr: "Sushi", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Sushi (Rift of Gods / RoG) bonuses. 8 rows.",
    idx: { 5: "per-tier unlock state (100). UniqueSushi = count of LEADING consecutive entries >= 0 (52 here); the first negative stops the count." },
    evidence: "N.js _customBlock_SushiStuff(\"RoG_BonusQTY\",b,e) @10940509: `UniqueSushi > b || e==99 ? CustomLists.Research[37][b] : 0`. Research[36][7]=\"}x_artifact_find_chance\", Research[37][7]=\"30\".",
    confidence: "confirmed",
  },
  FarmUpg: {
    name: "farmingUpgrades", attr: "FarmUpg", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Farming: market/exotic upgrade levels (100).",
    idx: {
      10: "OGunlocked gate (>=1 means unlocked)",
      65: "market exotic 45 = 5_LEAF_CLOVER (}x Artifact Find Chance). General rule: exotic e lives at FarmUpg[20+e].",
    },
    evidence: "N.js _customBlock_FarmingStuffs(\"ExoticBonusQTY\",b,0) @10577033 builds ExoticFarmBon from FarmUpg[20+e] and MarketExoticInfo[e][3]/[4]. MarketExoticInfo[45]=[\"5_LEAF_CLOVER\",\"}x_Artifact_Find_Chance...\",\"79\",\"30\",\"1\",\"2\"].",
    confidence: "confirmed",
  },
  FarmCrop: {
    name: "farmCrops", attr: "FarmCrop", family: false, scope: "account", agg: null, governs: null,
    shape: "dict", parse: "json",
    desc: "Owned crop quantities, keyed by crop id string -> quantity.",
    idx: { "<cropId>": "quantity owned (float)" },
    evidence: "N.js W6item1 handler decrements FarmCrop.h[\"4\"]; W6item2 decrements FarmCrop.h[\"30\"] — confirms dict of cropId -> qty.",
    confidence: "confirmed",
  },
  FarmRank: {
    name: "farmRanks", attr: "FarmRank", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Farming crop ranks. 3 rows.",
    idx: {
      0: "per-crop rank level; feeds LankRankEXPreq = (10 + 7*rank + 25*floor(rank/5)) * 1.11^rank",
      1: "per-crop rank EXP (inferred from position; not individually confirmed)",
      2: "per-crop aux (inferred; not individually confirmed)",
    },
    evidence: "N.js _customBlock_FarmingStuffs(\"LankRankEXPreq\") ~10568100 reads FarmRank[0][b]; ~5590000 sums FarmRank[0] into TomeQTY[77]. Rows 1/2 not individually confirmed.",
    confidence: "confirmed",
  },
  FarmPlot: {
    name: "farmPlots", attr: "FarmPlot", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Farming plots (36 plots), each a 7-field tuple. SHAPE is certain; FIELD MEANINGS are not.",
    idx: { "[i][0..6]": "per-plot fields. NOT traced to semantics — deliberately left undocumented rather than guessed." },
    evidence: "N.js reads FarmPlot[x][0..6] in ~146 places; init ~19290000 pushes a 3+ element list. No sub-index was traced to a meaning.",
    confidence: "inferred",
  },
  Grimoire: {
    name: "grimoire", attr: "Grimoire", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Grimoire (Death Bringer) upgrade levels. Initialized to 100 zeros.",
    idx: { 36: "all-Grimoire multiplier, applied as 1+x/100 to non-exempt upgrades. Exempt: 9,11,17,26,32,36,39,45." },
    evidence: "N.js _customBlock_Summoning(\"GrimoireUpgBonus\",b,0): Grimoire[b] * CustomLists.GrimoireUpg[b][5], times (1+GrimoireUpgBonus(36)/100) unless b is exempt.",
    confidence: "confirmed",
  },
  Arcane: {
    name: "arcaneCultivation", attr: "Arcane", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Arcane Cultivation (Tesseract) upgrade levels. Initialized to 100 zeros.",
    idx: { 39: "all-Arcane multiplier (1+x/100). Exempt: 3,7,8,10,13,16,20,25,26,28,33,35,39,40,43,45,48,57,58." },
    evidence: "N.js _customBlock_ArcaneType(\"ArcaneUpgBonus\",b,e): Arcane[b] * CustomLists.ArcaneUpg[b][5], times (1+ArcaneUpgBonus(39)/100) unless exempt. e==999 is a sentinel.",
    confidence: "confirmed",
  },
  Compass: {
    name: "compass", attr: "Compass", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Windwalker/Compass (World 6). 5 rows.",
    idx: {
      0: "compass upgrade levels (parallel to CustomLists.CompassUpg)",
      1: "per-Titan state (padded to CustomLists.Titans.length)",
      3: "list of monster types that already dropped a Tempest Medallion",
    },
    evidence: "N.js _customBlock_Windwalker(\"CompassBonus\",b,0): Compass[0][b] * CompassUpg[b][5], gated on CompassUpg[b][9]. Compass[3] used via D.contains(...) for medallion dedup.",
    confidence: "confirmed",
  },
  Rift: {
    name: "rift", attr: "Rift", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "The Rift. 10 entries; only 0-4 are read by the client.",
    idx: {
      0: "rift level/stage (gates checks like `24 < Rift[0]`)",
      1: "current rift task progress",
      2: "string field (reset to \"\")",
      3: "numeric (reset to 0)",
      4: "numeric",
    },
    evidence: "N.js reset block ~19280000 sets Rift[0]=0, Rift[1]=0, Rift[2]=\"\", Rift[3]=0. _customBlock_RiftStuff(\"RiftTaskProgress\") mutates Rift[1]. Indices 5-9 never read.",
    confidence: "confirmed",
  },
  Dream: {
    name: "equinoxDream", attr: "Dream", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Equinox: bar fill + upgrade levels (24 entries).",
    idx: {
      0: "Equinox bar fill (clamped to Dreamstuff('BarFillReq',0); set to 999 on reset)",
      2: "Equinox upgrade 0 = Clouds owned (CloudsOwned = round(min(5, Dream[2])))",
      "2+i": "Equinox upgrade i level, i=0..13",
    },
    evidence: "N.js `Dream[0]=Math.min(Dreamstuff(\"BarFillReq\",0), Dream[0]+...)`; IsBarFULL compares Dream[0] >= ceil(BarFillReq); upgrade sum loop `for(d=0;14>d;) DreamDN1 += Dream[2+f]`.",
    confidence: "confirmed",
  },
  WeeklyBoss: {
    name: "weeklyBossDreams", attr: "WeeklyBoss", family: false, scope: "account", agg: null, governs: null,
    shape: "dict", parse: "json",
    desc: "Equinox dreams + weekly boss state.",
    idx: {
      "d_<n>": "dream n status; -1 = COMPLETED. Dreamstuff('CloudBonus',n) returns 1 iff d_n === -1.",
      "UI_*": "UI state (UI_d, UI_b, UI_i, UI_h)",
      "set<n>": "set/loadout state (set0..set5)",
      g: "weekly boss damage key",
    },
    evidence: "N.js _customBlock_Dreamstuff(\"CloudBonus\",b) ~10420000: `return -1==WeeklyBoss.h[\"d_\"+b] ? 1 : 0`. Reset loop deletes keys starting with \"d_\".",
    confidence: "confirmed",
  },
};
