/* savemap/w67.mjs — World 6-7 + endgame save keys.
 * Ground truth: N.js (decompiled client), verified against a real save.
 * Most of these converge on `_customBlock_Sailing("BoatArtiMulti")` — see artifactchance.mjs.
 */
export default {
  Holes: {
    name: "caverns", attr: "Holes", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "World 5 The Caverns: villagers, monuments, buildings, fountain, cosmo, resources.",
    idx: {
      1: "villager levels [Explorer,Engineer,Conjuror,Measurer,Librarian,Elder,?,?] (names: CustomLists.HolesInfo[20])",
      4: "cosmo upgrade levels; CosmoBonusQTY(b,e) reads Holes[4+b][e]",
      9: "cavern resource currencies (38). [9][11] = Natural Notes, feeds B_UPG 55",
      13: "building/upgrade unlock flags (150). B_UPG(b) returns 0 when Holes[13][b]==0",
      14: "Bravery state; [0] feeds Bravery_MinDMG/MaxDMG",
      15: "monument bonus levels, flat index = 10*monument + slot. [15][12] = Monument of Justice artifact-find level; [15][19] = Justice Bonuses Multi",
      16: "feeds B_UPG 45 (sum -> 1.1^floor(sum/25))",
      31: "fountain upgrade levels [waterType][upgIdx]",
      32: "fountain marble ranks [waterType][upgIdx]",
    },
    evidence: "N.js _customBlock_Holes(\"MonumentROGbonuses\",b,e) ~10748038 reads Holes[15][10*b+e] with coeff CustomLists.HolesInfo[37][10*b+e]; HolesInfo[32][12]=\"}x_Artifact|Find_Chance\". _customBlock_Holes(\"B_UPG\",55) ~10731680 reads Holes[9][11]; HolesBuildings[55]=\"Tune_of_Artifaction\".",
    confidence: "confirmed",
  },
  Summon: {
    name: "summoning", attr: "Summon", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Summoning: SUMMON UPGRADE levels + the list of defeated summoning enemies.",
    idx: {
      0: "Summon Upgrade levels (Ya.SummonUPG, 82 rows). Summon[0][b] = level of army-build upgrade b. SummUpgBonus(b) = (1+SumStoneTrialz(colour))*level*SummonUPG[b][6]. sum(Summon[0]) = GenINFO[170]*100 (per-100 totalUpgradeLevels counter). gamedata-w6-summoning.mjs.",
      1: "defeated summon enemy names. Names starting with 'rift' are EXCLUDED from WinBonus.",
    },
    evidence: "N.js _customBlock_Summoning(\"WinBonus\",..) @10671364 iterates Summon[1]. _customBlock_Summoning(\"SummUpgBonus\",b,0) @10665909 reads Summon[0][b]*SummonUPG[b][6]; \"UpgCost\" @10667117 reads Summon[0][b]. this._DN5=sum(Summon[0]); GenINFO[170]=floor(DN5/100).",
    confidence: "confirmed",
  },
  UpgVault: {
    name: "vaultUpgrades", attr: "UpgVault", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Summoning Vault upgrade levels. 90 REAL upgrades (CustomLists.UpgradeVault.length===90); the save array is padded to 100 — indices 90-99 are dead.",
    idx: {
      63: "Artifact_Find_Chance (+% per level; UpgradeVault[63][5] coeff = 1)",
      32: "Vault Mastery I (multiplies upgrades b<32)",
      61: "Vault Mastery II (multiplies 32<=b<61)",
      89: "Vault Mastery III (multiplies 61<=b<89; itself exempt)",
    },
    evidence: "N.js _customBlock_Summoning(\"VaultUpgBonus\",b,0) @10637795: level * UpgradeVault[b][5], times a mastery multiplier chosen by band. UpgradeVault[63][0]==\"Artifact_Find_Chance\".",
    confidence: "confirmed",
  },
  Ninja: {
    name: "ninja", attr: "Ninja", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Sneaking/Ninja: 108 entries. Per-twin state, inventory, equipment, upgrades, charms, beanstalk. PARTIALLY MAPPED.",
    idx: {
      "b (0..)": "per-twin/character row; Ninja[b][0] = twin b's current FLOOR (0..11). GenerateItem reads NinjaInfo[12+Ninja[b][0]] for the floor's drop table.",
      102: "W6 item currency + jade-emporium unlock bitstring. [102][9] = jade emporium unlock letters (EmporiumBonus(b) = Ninja[102][9].indexOf(Number2Letter[b]) != -1). gamedata-w6-sneaking.mjs.",
      103: "NINJA KNOWLEDGE upgrade levels (na.NinjaUpg, 29 rows). NLbonuses(b) = Ninja[103][b]*NinjaUpg[b].modifier (default branch). [103][13]=Way_of_Stealth, [103][23]=Shhhhhhhhhhh (stealth). gamedata-w6-sneaking.mjs.",
      104: "BEANSTALK ranks: Ninja[104][e] = rank of beanstalk-slot e (0 unplanted, 1=10k, 2=100k, 3=1M). _customBlock_GoldFoodBonuses reads it; slot order = NinjaInfo[29] triplets (gamedata-w6-beanstalk.mjs BEANSTALK_SLOTS).",
      106: "list of item names already obtained (drop dedup)",
      107: "PRISTINE CHARM unlock flags (23, NjTrP0..22). [107][2]=Glowing_Veil (}x Artifact Find); [107][8]=Crystal_Comb (}x Summoning Winner Bonuses); [107][14]=Gumm_Stick (+% Golden Food). gamedata-w6-sneaking.mjs.",
    },
    evidence: "N.js _customBlock_Ninja(\"PristineBon\",b,0) @10616776: `return 1==Ninja[107][b] ? CustomMaps.NjEQ[\"NjTrP\"+b][3] : 0` (exactly 23 NjTrP keys). \"NLbonuses\" reads Ninja[103][b]; \"Stealth\" reads Ninja[b][0] as floor; _customBlock_GoldFoodBonuses reads Ninja[104][e]. \"EmporiumBonus\" reads Ninja[102][9].",
    confidence: "confirmed",
  },
  Spelunk: {
    name: "spelunking", attr: "Spelunk", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Spelunking (Caverns minigame): cave unlocks, depths, POW, shop upgrades, discoveries, lore.",
    idx: {
      0: "cave unlock flags (15)",
      1: "per-cave depth/progress (15)",
      2: "per-cave POW/currency (15)",
      5: "spelunk shop upgrade levels (90 slots; only rows 0-52 real, 53-89 dead padding). ShopUpgBonus(b,1) = SpelunkUpg[b].coeff * max(0, Spelunk[5][b]). gamedata-w7-spelunking.mjs SPELUNK_SHOP.",
      6: "DISCOVERY NAMES — array of discovered rock names (87 of 99 possible). Its LENGTH feeds 1.02^n artifact find, 1.01^n class EXP, 1.05^n collectible, 1.03^n EXP.",
      9: "gaming palette levels (37); [9][5] feeds GamingStatType(\"PaletteBonus\",5,0)",
      11: "ADVICE FISH (\"BigFish\") upgrade levels (6 rows). Spelunk[11][b] = level of Advice Fish upgrade b; BigFishBon(b) = level/(100+level) * BIG_FISH[b].coeff. gamedata-w7-spelunking.mjs BIG_FISH.",
      13: "CORAL REEF BUILDING levels (6 rows). Spelunk[13][b] = level of Coral Reef building b; ReefCost(b) = CoralReef[b].costBase * costGrowth^Spelunk[13][b]. gamedata-w7-coralreef.mjs CORAL_REEF_BUILDINGS.",
      18: "LEGEND TALENT levels spent per talent (50 slots; ids 0-39 real, 40-49 filler). Spelunk[18][b] = points spent on Legend Talent b; LegendPTS_bonus(b) = round(Spelunk[18][b] * LegendTalents[b][2]); LegendPTS_spent = round(sum(Spelunk[18][0..49])). gamedata-w7-legend.mjs / bonuses/thingies.mjs.",
      45: "ZENITH MARKET owned levels (10 rows). Spelunk[45][b] = level of Zenith Market row b; ZenithMarketBonus(b) = floor(ZenithMarket[b].coeff * Spelunk[45][b]). gamedata-w7-zenith.mjs / bonuses/zenith.mjs.",
      46: "equipment hat names",
    },
    evidence: "N.js @12402022 `Spelunk[6].push(CustomLists.SpelunkRocks[cave][rock][0])`; `D.contains(Spelunk[6], name)` is the discovered check @12380018. SpelunkRocks = 9 caves, 99 rocks. GamingUpg[26]=\"1.02x_Artifact_chance_per_Spelunk_Discovery\". idx 18: N.js LegendPTS_spent @10709527 loops `Spelunk[18][e]` e=0..49; idx 11: BigFishBon @10861944 reads Spelunk[11][b]; idx 13: ReefCost @10713182 reads Spelunk[13][b]; idx 45: ZenithMarketBonus @10701968 reads Spelunk[45][b].",
    confidence: "confirmed",
  },
  Research: {
    name: "research", attr: "Research", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Research (Minehead/grid): grid node levels, occurrence tags, observations, farming stickers.",
    idx: {
      0: "grid node LEVELS (240; parallel to CustomLists.ResGridSquares)",
      1: "grid node OCCURRENCE index (240); -1 = none, else index into CustomLists.Research[5] = [25,15,50,20,20,35,25,30,35,60] (percent)",
      7: "research progress/AFK state; [7][4] = a Minehead unlock-tier counter — Minehead(\"BonusQTY\",b,0) = Research[7][4] > b ? Research[20][b] : 0.",
      8: "MINEHEAD Depth-Charge SHOP levels (30 rows; MineheadUPG). Research[8][b] = level of minehead shop upgrade b; UpgradeQTY = MineheadUPG[b][3] * Research[8][b]. gamedata-w7-minehead.mjs MINEHEAD_SHOP.",
      9: "FARMING STICKER counts (12; parallel to CustomLists.Research[23] names and [25] coeffs). [9][2] = Chocotastic Muffin Sticker (artifact find).",
      11: "observations list (length feeds Grid_Bonus 67/68/107)",
      12: "GLIMBO per-trade counts (22 slots; SAVE array, distinct from CustomLists.Research[12] tier ids). Research[12][b] = times Glimbo trade slot b has been used; feeds Glimbo_Cost/GlimboTotalTrades. gamedata-w7-research.mjs GLIMBO_TRADES.",
    },
    evidence: "N.js _customBlock_ResearchStuff(\"Grid_Bonus\",b,0) @10901346: ResGridSquares[b][2] * Research[0][b] * (Research[1][b]==-1 ? 1 : 1+Research[5][Research[1][b]]/100) * max(1, Grid_Bonus_Allmulti). ResGridSquares[109][0]=\"Transcendent_Artifacts\", [106][0]=\"The_Maw\". idx 8: Minehead UpgradeQTY @10918638 reads Research[8][b]; idx 12: Glimbo_Cost @10919446 reads Research[12][b].",
    confidence: "confirmed",
  },
  Sushi: {
    name: "sushi", attr: "Sushi", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Sushi (Rift of Gods / RoG) bonuses. 8 rows.",
    idx: { 5: "per-tier unlock state (100). UniqueSushi = count of LEADING consecutive entries >= 0 (52 here); the first negative stops the count." },
    evidence: "N.js _customBlock_SushiStuff(\"RoG_BonusQTY\",b,e) @10940509: `UniqueSushi > b || e==99 ? CustomLists.Research[37][b] : 0`. Research[36][7]=\"}x_artifact_find_chance\", Research[37][7]=\"30\".",
    confidence: "confirmed",
  },
  FarmUpg: {
    name: "farmingUpgrades", attr: "FarmUpg", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Farming: market/exotic upgrade levels (100).",
    idx: {
      0: "currently selected seed tier for planting",
      1: "Magic Beans owned (Night Market currency; credited from BeanTradeQTY, N.js ~13876)",
      "2..9": "Day Market upgrade levels, rows 0-7 of MarketInfo (LAND_PLOTS, STRONGER_VINES, NUTRITIOUS_SOIL, SMARTER_SEEDS, BIOLOGY_BOOST, PRODUCT_DOUBLER, MORE_BEENZ, RANK_BOOST); accessed as FarmUpg[2+e+8*tab]",
      "10..17": "Night Market upgrade levels, rows 8-15 of MarketInfo (10 OVERGROWTH unlock, 11 EVOLUTION_GMO, 12 SPEED_GMO, 13 OG_FERTILIZER, 14 EXP_GMO, 15 LAND_RANK unlock, 16 VALUE_GMO, 17 SUPER_GMO)",
      18: "unused (never referenced in N.js)",
      19: "Instagrow charges (consumed ~18802; +2/day per GemItemsPurchased[139] ~24988)",
      65: "market exotic 45 = 5_LEAF_CLOVER (}x Artifact Find Chance). General rule: exotic e lives at FarmUpg[20+e]; array grows past 20 on exotic buys.",
    },
    evidence: "N.js _customBlock_FarmingStuffs(\"ExoticBonusQTY\",b,0) @10577033 builds ExoticFarmBon from FarmUpg[20+e] and MarketExoticInfo[e][3]/[4]. MarketExoticInfo[45]=[\"5_LEAF_CLOVER\",\"}x_Artifact_Find_Chance...\",\"79\",\"30\",\"1\",\"2\"].",
    confidence: "confirmed",
  },
  FarmCrop: {
    name: "farmCrops", attr: "FarmCrop", family: false, scope: "account", agg: null, governs: null,
    shape: "dict", parse: "json",
    desc: "Owned crop quantities, keyed by crop id string -> quantity.",
    idx: { "<cropId>": "quantity owned (float)" },
    evidence: "N.js W6item1 handler decrements FarmCrop.h[\"4\"]; W6item2 decrements FarmCrop.h[\"30\"] — confirms dict of cropId -> qty.",
    confidence: "confirmed",
  },
  FarmRank: {
    name: "farmRanks", attr: "FarmRank", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Farming land ranks. 3 rows.",
    idx: {
      0: "per-PLOT Land Rank level (36 slots); feeds LankRankEXPreq = (10 + 7*rank + 25*floor(rank/5)) * 1.11^rank",
      1: "per-PLOT rank EXP progress (36 slots); gains on collect (\"j\" handler ~19285), levels up while >= req",
      2: "Land Rank Database upgrade levels (20 slots, parallel to NinjaInfo[34..37]); points spent = sum; LankRankPTSleft = sum(FarmRank[0]) - sum(FarmRank[2])",
    },
    evidence: "N.js _customBlock_FarmingStuffs(\"LankRankEXPreq\") reads FarmRank[0][b]; collect \"j\" handler ~19285-19286 adds rank XP to FarmRank[1][plot] and loops level-ups into FarmRank[0][plot]; \"LankRankPTSleft\" ~17926 sums FarmRank[0][0..35] minus FarmRank[2][0..19]; ~5590000 sums FarmRank[0] into TomeQTY[77].",
    confidence: "confirmed",
  },
  FarmPlot: {
    name: "farmPlots", attr: "FarmPlot", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Farming plots (36 plots), each a 7-field tuple. Fully decoded 2026-07-18.",
    idx: {
      "[i][0]": "seed tier (-1 empty, 0-5 Basic..Glassy, 6 Medal); index into SeedInfo and Research[9] sticker counts",
      "[i][1]": "growth progress toward GrowthReq. Only accrues while [4]==0; resets to 0 on collect",
      "[i][2]": "evolution progress (crop offset within tier; absolute crop id = SeedInfo[tier].cropIdMin + [2]). +1 on rand<NextCropChance when [1] crosses GrowthReq and [3]==0",
      "[i][3]": "evolution-lock flag (block-evolution tool); 1 suppresses the [2] increment",
      "[i][4]": "crops on vine: 0 = still growing, else CropsOnVine result set when growth completes. While nonzero, ALL growth flows into [6] instead of [1] — so evolution rolls happen exactly once per collect cycle",
      "[i][5]": "OG (overgrowth) level; +1 per successful NextOGchance roll; multiplier = min(1e9, 2^[5]); also megacrop sticker weight 2^[5]",
      "[i][6]": "overgrowth-time accumulator; consumed in GrowthReq chunks (one OG roll each; batched 1000x/50x for tiny chances), hard-capped at 1e4*GrowthReq",
    },
    evidence: "N.js farming tick, the \"g\" TRIGGEREDtext handler ~line 19309-19318 (read directly 2026-07-18): [4]!=0 routes growth into [6]; [1]+dt*GrowthRate >= GrowthReq rolls NextCropChance once (gated [3]==0), increments [2], sets [4]=CropsOnVine; while([6]>=GrowthReq) rolls NextOGchance, increments [5], attempts megacrop with weight 2^[5]; collect handler ~18805 adds [4]*OGmulti*CropsBonusValue to FarmCrop then zeroes [1],[4],[5],[6].",
    confidence: "confirmed",
  },
  Grimoire: {
    name: "grimoire", attr: "Grimoire", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Grimoire (Death Bringer) upgrade levels. Initialized to 100 zeros.",
    idx: { 36: "all-Grimoire multiplier, applied as 1+x/100 to non-exempt upgrades. Exempt: 9,11,17,26,32,36,39,45." },
    evidence: "N.js _customBlock_Summoning(\"GrimoireUpgBonus\",b,0): Grimoire[b] * CustomLists.GrimoireUpg[b][5], times (1+GrimoireUpgBonus(36)/100) unless b is exempt.",
    confidence: "confirmed",
  },
  Arcane: {
    name: "arcaneCultivation", attr: "Arcane", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Arcane Cultivation (Tesseract) upgrade levels. Initialized to 100 zeros.",
    idx: { 39: "all-Arcane multiplier (1+x/100). Exempt: 3,7,8,10,13,16,20,25,26,28,33,35,39,40,43,45,48,57,58." },
    evidence: "N.js _customBlock_ArcaneType(\"ArcaneUpgBonus\",b,e): Arcane[b] * CustomLists.ArcaneUpg[b][5], times (1+ArcaneUpgBonus(39)/100) unless exempt. e==999 is a sentinel.",
    confidence: "confirmed",
  },
  Compass: {
    name: "compass", attr: "Compass", family: false, scope: "account", agg: null, governs: null,
    shape: "nested", parse: "json",
    desc: "Windwalker/Compass (World 6). 5 rows.",
    idx: {
      0: "compass upgrade levels (parallel to CustomLists.CompassUpg)",
      1: "per-Titan state (padded to CustomLists.Titans.length)",
      3: "list of monster types that already dropped a Tempest Medallion",
    },
    evidence: "N.js _customBlock_Windwalker(\"CompassBonus\",b,0): Compass[0][b] * CompassUpg[b][5], gated on CompassUpg[b][9]. Compass[3] used via D.contains(...) for medallion dedup.",
    confidence: "confirmed",
  },
  Rift: {
    name: "rift", attr: "Rift", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "The Rift. 10 entries; only 0-4 are read by the client.",
    idx: {
      0: "rift level/stage (gates checks like `24 < Rift[0]`)",
      1: "current rift task progress",
      2: "string field (reset to \"\")",
      3: "numeric (reset to 0)",
      4: "numeric",
    },
    evidence: "N.js reset block ~19280000 sets Rift[0]=0, Rift[1]=0, Rift[2]=\"\", Rift[3]=0. _customBlock_RiftStuff(\"RiftTaskProgress\") mutates Rift[1]. Indices 5-9 never read.",
    confidence: "confirmed",
  },
  Dream: {
    name: "equinoxDream", attr: "Dream", family: false, scope: "account", agg: null, governs: null,
    shape: "number[]", parse: "raw",
    desc: "Equinox: bar fill + upgrade levels (24 entries).",
    idx: {
      0: "Equinox bar fill (clamped to Dreamstuff('BarFillReq',0); set to 999 on reset)",
      2: "Equinox upgrade 0 = Clouds owned (CloudsOwned = round(min(5, Dream[2])))",
      "2+i": "Equinox upgrade i level, i=0..13",
    },
    evidence: "N.js `Dream[0]=Math.min(Dreamstuff(\"BarFillReq\",0), Dream[0]+...)`; IsBarFULL compares Dream[0] >= ceil(BarFillReq); upgrade sum loop `for(d=0;14>d;) DreamDN1 += Dream[2+f]`.",
    confidence: "confirmed",
  },
  WeeklyBoss: {
    name: "weeklyBossDreams", attr: "WeeklyBoss", family: false, scope: "account", agg: null, governs: null,
    shape: "dict", parse: "json",
    desc: "Equinox dreams + weekly boss state.",
    idx: {
      "d_<n>": "dream n status; -1 = COMPLETED. Dreamstuff('CloudBonus',n) returns 1 iff d_n === -1.",
      "UI_*": "UI state (UI_d, UI_b, UI_i, UI_h)",
      "set<n>": "set/loadout state (set0..set5)",
      g: "weekly boss damage key",
    },
    evidence: "N.js _customBlock_Dreamstuff(\"CloudBonus\",b) ~10420000: `return -1==WeeklyBoss.h[\"d_\"+b] ? 1 : 0`. Reset loop deletes keys starting with \"d_\".",
    confidence: "confirmed",
  },
};
