/* gamedata-w5-hole.mjs — The Hole (Caverns) villager, jar, and cavern-unlock static data,
 * extracted verbatim from N.js (v1.19-era). GENERATED by one-off extraction scripts
 * (scratchpad, not committed); refresh after a major patch.
 *
 * SCOPE: this file covers ONLY the villager table + EXP/hr formula + jar types/collectibles +
 * cavern unlock order for The Hole (World 5's "Caverns" system, save attribute `Holes`, plus a
 * separate top-level `Jars` save attribute for physical jar-container instances — neither is
 * currently mapped in savemap/w67.mjs beyond the `Holes` idx entries already there). The Hole is
 * a second-Sailing-sized system (18 caverns, ~90 Engineer blueprints, a 3-water/20-upgrade
 * Fountain, 20 Studies, Cosmo Majiks, Monuments, 11 Measurements) — everything besides
 * villagers/jars/caverns is explicitly OUT OF SCOPE here; see the OUT-OF-SCOPE POINTERS block
 * at the bottom for where those systems live in N.js for a future extraction pass.
 *
 * MAIN DISPATCHER: `m._customBlock_Holes=function(d,b,e){...}`, N.js:18222, with a sibling
 * `m._customBlock_Holes2=function(d,b,e){...}` (N.js:18308) that Holes falls through to
 * (`...:m._customBlock_Holes2(d,b,e)}`) for unmatched case strings. Both were read in full for
 * this pass (N.js:18222-18327ish).
 *
 * STATIC TABLE SOURCE: `na.HolesInfo=function(){return[...]}`, N.js:23586 — ONE giant reflowed
 * array-of-arrays literal (77 sub-arrays, indices 0-76) with NO internal line breaks in the
 * source; N.js's reflow just wraps it at some column width mid-statement — same gotcha
 * documented in gamedata-w4-rift.mjs for na.RiftStuff. Every HolesInfo[N] table cited below
 * shares this single N.js:23586 origin line. Extracted by locating the
 * `na.HolesInfo=function(){return[` marker and bracket-matching the array literal (respecting
 * string-quote nesting) with a one-off Python script, then `eval()`-ing the isolated literal in
 * Node to get real JS values — far safer than transcribing ~34KB of minified text by hand.
 * `na.HolesBuildings=function(){return[...]}` (N.js:23616, 107 entries) is the Engineer
 * blueprint table — OUT OF SCOPE, cited only where it corroborates a name below.
 * -------------------------------------------------------------------------------------------- */

/** ------------------------------------------------------------------------------------------
 * 1. VILLAGERS — HolesInfo[20] (N.js:23586), 8 slots, only 5 are real/active.
 *
 * `Holes[1][b]` = current level of villager b (`"VillagerLV"==d`, N.js:18224, verbatim:
 *   `return a.engine.getGameAttribute("Holes")[1][b|0]`).
 * Names/flavor below are the RAW HolesInfo[20][b] strings with `_@_`/`_@___@_` (in-game
 * line-break markers) left as literal underscores so nothing is lost in translation; `name` is
 * the cleaned-up first segment.
 *
 * Only villager slots 0-4 have a working EXP curve (see VILLAGER_EXP_REQ below) — slots 5-7
 * fall through to a `10*Math.pow(10,20)` EXP requirement (N.js:18227), i.e. permanently
 * uninvestable. Slot 5 ("Elder") at least has a name in HolesInfo[20][5]; slots 6/7 are bare
 * "???" — confirmed unreleased/reserved villager slots as of this game version, NOT a
 * transcription gap.
 *
 * VERIFIED against savemap/w67.mjs's pre-existing comment on the `Holes` key
 * (`1: "villager levels [Explorer,Engineer,Conjuror,Measurer,Librarian,Elder,?,?]"`) — exact
 * name-order match.
 * ------------------------------------------------------------------------------------------ */
export const VILLAGERS = [
  { idx: 0, name: "Explorer", active: true,
    raw: "Explorer_@___@_Each_LV_of_this_villager_unlocks_a_new_cavern!_@___@_Invest_opals_to_increase_their_XP/hr_using_that_blue_button!" },
  { idx: 1, name: "Engineer", active: true,
    raw: "Engineer_@___@_Each_LV_unlocks_3_new_schematics_to_create!_@_Every_5_LVs_unlocks_an_additional_schematic!__@___" },
  { idx: 2, name: "Conjuror", active: true,
    raw: "Conjuror_@___@_Each_LV_gives_+1_Majik_Point_to_put_into_permanent_bonuses!" },
  { idx: 3, name: "Measurer", active: true,
    raw: "Measurer_@___@_Each_LV_gives_a_new_bonus_to_upgrade!_The_multi_goes_up_as_you_increase_its_IdleOn_stat,_shown_in_parenthesis!__@___" },
  { idx: 4, name: "Librarian", active: true,
    raw: "Librarian_@___@_Send_them_to_study_specific_caverns_to_discover_powerful_bonuses!_Each_LV_boosts_his_study_rate_by_+5%___" },
  { idx: 5, name: "Elder", active: false, raw: "Elder",
    note: "name only, no flavor text, no working EXP curve (VillagerExpREQ falls to 1e21) — unreleased/reserved" },
  { idx: 6, name: "???", active: false, raw: "???", note: "placeholder, unreleased/reserved" },
  { idx: 7, name: "???", active: false, raw: "???", note: "placeholder, unreleased/reserved" },
];

/** VillagerExpREQ(b, L) — the EXP needed to advance villager b FROM level L, transcribed
 *  verbatim from N.js:18225-18227 (`"VillagerExpREQ"==d`). L = current VillagerLV(b,0).
 *
 *  b=0 (Explorer) has an extra wrinkle beyond the other 4 curves: a `DoOnceREAL` (a global
 *  one-time-event/account flag counter, not chased further — out of scope) gated multiplier
 *  `Math.pow(3.4, min(1,max(0,floor((1e5+DoOnceREAL)/100247.3))) * max(0,L-12))`. This reads as
 *  a one-time balance-migration flag that flips the post-LV12 curve steepness once
 *  `DoOnceREAL >= 247.3` (solving `floor((1e5+x)/100247.3)>=1`) — UNRESOLVED semantics (what
 *  DoOnceREAL's index/meaning is, and whether it's already flipped on live accounts), but the
 *  formula itself is transcribed verbatim and the `doOnceReal` param defaults to a value that
 *  makes the flag active (matches expected live-game behavior on any non-fresh account; pass 0
 *  to see the pre-patch curve). */
export function villagerExpReq(b, L, doOnceReal = 200000) {
  if (b === 0) {
    if (L === 1) return 5; // N.js: `1==VillagerLV(b,0)&&0==b?5:...` — special-cased
    const patchFlag = Math.min(1, Math.max(0, Math.floor((1e5 + doOnceReal) / 100247.3)));
    return 10 * (-1.5 + (10 + 7 * Math.pow(L, 2.1)) * Math.pow(2.1, L) *
      (1 + 0.75 * Math.max(0, L - 4)) *
      Math.pow(3.4, patchFlag * Math.max(0, L - 12)));
  }
  if (b === 1) return 30 * (10 + 6 * Math.pow(L, 1.8)) * Math.pow(1.57, L);
  if (b === 2) return 50 * (10 + 5 * Math.pow(L, 1.7)) * Math.pow(1.4, L);
  if (b === 3) return 120 * (30 + 10 * Math.pow(L, 2)) * Math.pow(2, L);
  if (b === 4) return 500 * (10 + 5 * Math.pow(L, 1.3)) * Math.pow(1.13, L);
  return 10 * Math.pow(10, 20); // slots 5-7: unreleased, effectively unreachable
}

/** ------------------------------------------------------------------------------------------
 * 2. VILLAGER EXP/HR FORMULA — `"VillagerExpPerHour"==d`, N.js:18227-18229 (one wrapped
 * statement; stitched with `sed -n '18222,18260p' N.js | tr -d '\n'` per the task's guidance on
 * reflowed lines). Transcribed VERBATIM below, both as a raw-expression comment (so nothing is
 * lost/reinterpreted) and as a structured term list (VILLAGER_EXP_PER_HOUR_TERMS) with N.js
 * accessor + category for each of the ~29 individual bonus-contributing function calls found.
 *
 * RAW (N.js:18227-18229, `d`/`b`/`e` = case-string/villager-idx/unused; `HoleozDxp` is a scratch
 * var on DNSM, re-set per branch):
 *
 *   if (b==0 && CavernsOwned(0,0) < 13) HoleozDxp = Math.pow(1.5, OptionsListAccount[355]);
 *   else HoleozDxp = 1;
 *   if (b==2) HoleozDxp = 1 + Holes2("Fountain_BonTOT",0,14)/100;   // overwrites the above, b=2 only
 *
 *   return Math.max(1, HoleozDxp)
 *     * (100 + Holes("B_UPG",0,25))
 *     * Math.max(1,
 *           (1 + Windwalker("CompassBonus",59,0)/100)
 *         * (1 + Thingies("LegendPTS_bonus",12,0)/100)
 *         * (1 + Ninja("PristineBon",21,0)/100)
 *         * (1 + 2*Companions(13))
 *         * (1 + ArbitraryCode("StatueBonusGiven28")/100)
 *         * (1 + (Holes("JarCollectibleBonus",4,0) + Holes("JarCollectibleBonus",10,0)
 *                + Holes("JarCollectibleBonus",12,0) + Holes("JarCollectibleBonus",22,0)
 *                + Holes("JarCollectibleBonus",29,0) + Holes("JarCollectibleBonus",35,0)) / 100)
 *         * (1 + 25*Summoning("EventShopOwned",6,0)/100)
 *         * (1 + Thingies("LoreEpiBon",1,0)/100)
 *         * (1 + 50*BundlesReceived.bun_u/100)
 *       )
 *     * Holes[3][b]
 *     * (1 + Holes[23][b])
 *     * (1 + FarmingStuffs("ExoticBonusQTY",51,0)/100)
 *     * (1 + ArcadeBonus(38)/100)
 *     * (1 + Summoning("GrimoireUpgBonus",29,0)/100)
 *     * (1 + ArcaneType("ArcaneUpgBonus",32,0)/100)
 *     * (1 + Holes("CosmoBonusQTY",1,5) * Math.floor(Holes("LeastOpalsInVillager",0,0)/5) / 100)
 *     * (1 + ( Holes("MonumentROGbonuses",0,3) + Holes("MonumentROGbonuses",1,3)
 *            + Holes("MonumentROGbonuses",2,3)
 *            + ( Holes("MeasurementBonusTOTAL",7,0)
 *              + ( Math.floor(Holes[3][b]/10) * Holes("CosmoBonusQTY",1,0)
 *                + ( Holes("CosmoBonusQTY",1,1) * Holes("CosSchBlt",0,0)
 *                  + ( Holes("CosmoBonusQTY",1,2)
 *                    + ( Holes("B_UPG",48,0)
 *                      + ( Math.min(4*RunCodeOfTypeXforThingY("CardLv","caveB"),50)
 *                        + ( Holes("BellBonuss",1,0)
 *                          + ( Holes("MeasurementBonusTOTAL",0,0)
 *                            + ( Summoning("WinBonus",21,0) + Summoning("VaultUpgBonus",73,0) )
 *                          )
 *                        )
 *                      )
 *                    )
 *                  )
 *                )
 *              )
 *            )
 *          ) / 100 )
 *
 * Checklist cross-check (research-w5.md's ~20-term list — companion, statue, jar×5, event shop,
 * bundle, arcade, grimoire, tesseract, compass, charm, legend talent, tome, exotic market, cosmo
 * majik, monument, measurements, cards, bell, summoning): every category is present in ground
 * truth, but several have MORE than one N.js call site (jar=6 not 5, cosmo majik=4 calls,
 * monument=3 calls, measurements=2 calls, summoning=2 calls) — 29 individual bonus-contributing
 * calls total, not ~20. idleon-toolbox's hole.ts:561-566 (`jarBonuses`) independently transcribes
 * the SAME 6 jar-collectible indices (4,10,12,22,29,35) in the SAME order — exact match, 0
 * mismatch on that sub-term.
 * ------------------------------------------------------------------------------------------ */
export const VILLAGER_EXP_PER_HOUR_TERMS = [
  { category: "base-multiplier", accessor: "OptionsListAccount[355] -> pow(1.5,x)",
    note: "villager 0 (Explorer) ONLY, and ONLY while CavernsOwned<13; likely a gem-shop EXP-speed purchase count. Reset to 1 once b!=0 or CavernsOwned>=13." },
  { category: "base-multiplier", accessor: "Fountain_BonTOT(0,14) -> 1+x/100",
    note: "villager 2 (Conjuror) ONLY — overwrites the villager-0 special case above when b=2." },
  { category: "engineer", accessor: "B_UPG(0,25)", formula: "100 + x",
    note: "flat add to the 100-EXP/hr-per-opal base; +25 once 'Opal Dividends' blueprint (id 0) is built (verified: HolesBuildings[0] flavor text says 100->125 EXP/hr, N.js:23616)." },
  { category: "compass", accessor: "Windwalker.CompassBonus(59,0)" },
  { category: "legend talent", accessor: "Thingies.LegendPTS_bonus(12,0)" },
  { category: "charm", accessor: "Ninja.PristineBon(21,0)", note: "Ninja pristine charm bonus" },
  { category: "companion", accessor: "Companions(13)", formula: "1 + 2*x" },
  { category: "statue", accessor: "ArbitraryCode(\"StatueBonusGiven28\")" },
  { category: "jar", accessor: "JarCollectibleBonus(4,0)+(10,0)+(12,0)+(22,0)+(29,0)+(35,0)",
    note: "SIX collectible indices (not five — see JAR_COLLECTIBLES). idx into HolesInfo[67]." },
  { category: "event shop", accessor: "Summoning.EventShopOwned(6,0)", formula: "1 + 25*x/100" },
  { category: "tome", accessor: "Thingies.LoreEpiBon(1,0)" },
  { category: "bundle", accessor: "BundlesReceived.bun_u", formula: "1 + 50*x/100" },
  { category: "base", accessor: "Holes[3][b]", formula: "x (multiplicative base)",
    note: "opals invested in villager b — confirmed via LeastOpalsInVillager (N.js:18321) which scans this same array for the villager with fewest opals invested. Runtime save state, NOT a static table; Holes[3] is unmapped in savemap/w67.mjs's Holes.idx (currently documents 1,4,9,13,14,15,16,31,32 only) — flagging for the savemap-owning agent." },
  { category: "UNRESOLVED", accessor: "Holes[23][b]", formula: "1 + x",
    note: "per-villager additive term, RAW (not divided by 100, unlike every other additive term in this formula). The only other N.js references to Holes[23] (lines 35981, 36122) treat Holes[23][i] as a 0/1 dialogue/UI-state flag for an unrelated check — semantics for THIS use are unverified. Transcribed exactly as found; flagged unresolved per task instructions rather than guessed." },
  { category: "exotic market", accessor: "FarmingStuffs.ExoticBonusQTY(51,0)" },
  { category: "arcade", accessor: "ArcadeBonus(38)" },
  { category: "grimoire", accessor: "Summoning.GrimoireUpgBonus(29,0)" },
  { category: "arcane/tesseract", accessor: "ArcaneType.ArcaneUpgBonus(32,0)" },
  { category: "cosmo majik", accessor: "CosmoBonusQTY(1,5) * floor(LeastOpalsInVillager(0,0)/5)" },
  { category: "monument", accessor: "MonumentROGbonuses(0,3)+MonumentROGbonuses(1,3)+MonumentROGbonuses(2,3)",
    note: "Bravery(0) + Justice(1) + Wisdom(2) monuments; Compassion(3) is NOT included in this formula." },
  { category: "measurements", accessor: "MeasurementBonusTOTAL(7,0)" },
  { category: "cosmo majik", accessor: "floor(Holes[3][b]/10) * CosmoBonusQTY(1,0)",
    note: "scales with the villager's OWN opal investment (Holes[3][b] reused)." },
  { category: "cosmo majik", accessor: "CosmoBonusQTY(1,1) * CosSchBlt(0,0)",
    note: "CosSchBlt = count of built Engineer blueprints (Holes[13] flags set to 1), N.js:18296-18300." },
  { category: "cosmo majik", accessor: "CosmoBonusQTY(1,2)" },
  { category: "engineer", accessor: "B_UPG(48,0)" },
  { category: "cards", accessor: "min(4*RunCodeOfTypeXforThingY(\"CardLv\",\"caveB\"), 50)" },
  { category: "bell", accessor: "BellBonuss(1,0)" },
  { category: "measurements", accessor: "MeasurementBonusTOTAL(0,0)" },
  { category: "summoning", accessor: "Summoning.WinBonus(21,0)" },
  { category: "summoning", accessor: "Summoning.VaultUpgBonus(73,0)" },
];

/** ------------------------------------------------------------------------------------------
 * 3. JAR TYPES — HolesInfo[65] (N.js:23586), 10 entries (idx 0-9), NOT 5 as the research-brief
 * checklist assumed. `Holes[11][37]` = number of jar types currently unlocked (`"JarTypesOwned"
 * ==d`, N.js:18298); a new jar type costs `JarNewJar_Cost` and unlocking is capped at index 9
 * (`"CanWeAfford_Jar"==d` gates on `9 > Holes[11][37]`, N.js:18299). Matches the 10
 * HoleJar0.png..HoleJar9.png sprite assets.
 *
 * `name` for idx 0/1 is VERIFIED via a second, independent N.js string: HolesBuildings'
 * "Jar_Production_Line" blueprint flavor text (N.js:23636, verbatim): "...making 100
 * Simple_Jars would mean Tall_jars are 10% quicker to make!" — confirms "Simple Jar" (idx 0) and
 * "Tall Jar" (idx 1) as real in-game names, in order.
 *
 * `name` for idx 2-9 is UNVERIFIED — no literal N.js string for "Ornate Jar" / "Great Jar" /
 * "Artisan Jar" / "Epic Jar" / "Gilded Jar" / "Ceremony Jar" / "Heirloom Jar" was found anywhere
 * in N.js (grepped each individually). These names are carried over from idleon-toolbox's
 * `the-jars.ts` `jarNames` array as a best-effort label ONLY — `effect` (from HolesInfo[65]) is
 * the verified ground truth for each row; treat `name` for idx>=2 as a plausible label, not a
 * confirmed one.
 * ------------------------------------------------------------------------------------------ */
export const JAR_TYPES = [
  { idx: 0, name: "Simple Jar", nameConfidence: "verified", effect: "Contains a random basic rupie" },
  { idx: 1, name: "Tall Jar", nameConfidence: "verified", effect: "Has a {% chance to contain an Opal" },
  { idx: 2, name: "Ornate Jar", nameConfidence: "unverified", effect: "Has a {% chance to contain a new collectible" },
  { idx: 3, name: "Great Jar", nameConfidence: "unverified", effect: "Contains a random decent rupie" },
  { idx: 4, name: "Enchanted Jar", nameConfidence: "unverified", effect: "Has a {% chance to enchant a collectible, doubling its bonus" },
  { idx: 5, name: "Artisan Jar", nameConfidence: "unverified", effect: "Contains a white rupee" },
  { idx: 6, name: "Epic Jar", nameConfidence: "unverified", effect: "Contains a random elegant rupie" },
  { idx: 7, name: "Gilded Jar", nameConfidence: "unverified", effect: "Doubles the amount of rupies from the next jar opened" },
  { idx: 8, name: "Ceremony Jar", nameConfidence: "unverified", effect: "Contains a dark rupie" },
  { idx: 9, name: "Heirloom Jar", nameConfidence: "unverified", effect: "Contains the one and only master rupie" },
];

/** ------------------------------------------------------------------------------------------
 * 3b. JAR COLLECTIBLES — HolesInfo[67] (N.js:23586), 40 entries (idx 0-39). These are the
 * "Collectible" prizes found IN jars (distinct from the 10 JAR_TYPES containers above); their
 * per-collectible level (`Holes[24][idx]`, 0=not found, 1=found, 2+=enchanted tiers) feeds
 * `JarCollectibleBonus(idx,0)` (N.js:18310/18313, verbatim:
 *   `Holes[24][idx] * parseFloat(HolesInfo[67][idx].split("|")[1]) * (1+LegendPTS_bonus(29,0)/100)`
 * ) — six of these (idx 4,10,12,22,29,35) feed the villager EXP/hr formula above (all six are
 * literally "All villagers gain +{% more EXP" collectibles, confirmed by `effect` below).
 * `weight` = the `|N|` field (a per-collectible coefficient, used as the multiplier above — NOT
 * verified to be a drop-rarity weight despite the field position; naming is descriptive only).
 * Row count (40) matches idleon-toolbox's the-jars.ts collectibles map (`jarStuff.slice(0,40)`)
 * exactly — 0 mismatch.
 * ------------------------------------------------------------------------------------------ */
export const JAR_COLLECTIBLES = [
  { idx: 0, id: "ABNORMAL_RUPIE", weight: 20, effect: "Rupies found are worth +{% more. @ Current Rupie Value:$" },
  { idx: 1, id: "SAPPHIRE_DROPLET", weight: 10, effect: "Jar production rate is +{% faster." },
  { idx: 2, id: "EFFERVESCENT_DIAMOND", weight: 20, effect: "}x higher chance to find Opals in Tall Jars." },
  { idx: 3, id: "TORTOLE_ROCK", weight: 25, effect: "All rupies found are worth a whopping }x more!" },
  { idx: 4, id: "NATURAL_PEARL", weight: 15, effect: "All villagers gain +{% more EXP." },
  { idx: 5, id: "AMETHYST_HEARTSTONE", weight: 10, effect: "All skilling caverns require {% less Resources to get opals!" },
  { idx: 6, id: "AMBER_SQUARE", weight: 25, effect: "Rupies found are worth +{% more." },
  { idx: 7, id: "VERDANT_THORNS", weight: 25, effect: "}x higher chance to find new Collectibles." },
  { idx: 8, id: "VIOLENT_VIOLETS", weight: 20, effect: "All buckets get }x Bucket Fill Rate!" },
  { idx: 9, id: "BLUE_FABERGE_EGG", weight: 15, effect: "}x higher chance to enchant a Collectible" },
  { idx: 10, id: "SHADOW_PRISM", weight: 20, effect: "All villagers gain +{% more EXP." },
  { idx: 11, id: "BIG_BEEF_ROCK", weight: 25, effect: "}x faster Bell Ring Rate!" },
  { idx: 12, id: "EMERALD_ORE", weight: 30, effect: "All villagers gain +{% more EXP." },
  { idx: 13, id: "DAWN_PRISM", weight: 30, effect: "Rupies found are worth +{% more." },
  { idx: 14, id: "SWAMPSTONE", weight: 25, effect: "}x higher chance to find Opals in Tall Jars." },
  { idx: 15, id: "FROST_SPIRESTONE", weight: 12, effect: "Jar production rate is +{% faster." },
  { idx: 16, id: "ROSEMERALD", weight: 10, effect: "}x Faster study rate for villager Bolaia" },
  { idx: 17, id: "BLOOD_GLASS", weight: 40, effect: "All rupies found are worth a whopping }x more!" },
  { idx: 18, id: "SUNRISE_DIAMOND", weight: 25, effect: "}x higher chance to enchant a Collectible" },
  { idx: 19, id: "MINCERAFT_GEM", weight: 20, effect: "+{% Monument AFK Gain rate." },
  { idx: 20, id: "CRIMSON_SPADE", weight: 20, effect: "The harp produces }x more Notes!" },
  { idx: 21, id: "STAINED_GLASSDROP", weight: 35, effect: "Rupies found are worth +{% more." },
  { idx: 22, id: "TABULA_RASASTONE", weight: 32, effect: "All villagers gain +{% more EXP." },
  { idx: 23, id: "DEEP_BLUE_SQUARE", weight: 1, effect: "+{% Gambit PTS" },
  { idx: 24, id: "EARTHBOUND_GEODE", weight: 15, effect: "Jar production rate is +{% faster." },
  { idx: 25, id: "INFERNO_DROPLET", weight: 40, effect: "}x higher chance to find new Collectibles." },
  { idx: 26, id: "OCTOGONAL_GEM", weight: 30, effect: "}x higher chance to enchant a Collectible" },
  { idx: 27, id: "SOLARFANG", weight: 32, effect: "}x higher chance to find Opals in Tall Jars." },
  { idx: 28, id: "MYSTIC_ORE", weight: 50, effect: "All rupies found are worth a whopping }x more!" },
  { idx: 29, id: "ARCANE_PRISM", weight: 38, effect: "All villagers gain +{% more EXP." },
  { idx: 30, id: "MURKY_FABREGE_EGG", weight: 1, effect: "+{% Gambit PTS" },
  { idx: 31, id: "CORPORE_ROCK", weight: 1, effect: "Boosts a future cavern... futuuure..!" },
  { idx: 32, id: "TWILIGHT_PRISM", weight: 1, effect: "Boosts a future cavern... futuuure..!" },
  { idx: 33, id: "TEWBALL_ORBSTONE", weight: 40, effect: "Rupies found are worth +{% more." },
  { idx: 34, id: "MAD_MUSCLE_ROCK", weight: 40, effect: "}x higher chance to enchant a Collectible" },
  { idx: 35, id: "SUNROOT_SPLINTERS", weight: 40, effect: "All villagers gain +{% more EXP." },
  { idx: 36, id: "TWISTED_RUPIE", weight: 75, effect: "}x faster Bell Ring Rate!" },
  { idx: 37, id: "OVERLOADED_RELIC", weight: 1, effect: "Boosts a future cavern... futuuure..!" },
  { idx: 38, id: "SUNBURST_PEARL", weight: 1, effect: "Boosts a future cavern... futuuure..!" },
  { idx: 39, id: "BLOODFANG_SPIRES", weight: 1, effect: "Boosts a future cavern... futuuure..!" },
];

/** ------------------------------------------------------------------------------------------
 * 4. CAVERN UNLOCK ORDER — HolesInfo[68] (N.js:23586), 20 entries; the first 18 (idx 0-17) are
 * real, individually-named caverns, followed by TWO literal "BRUH" placeholder entries (idx
 * 18-19) — reserved/unbuilt future caverns, same pattern as gamedata-w4-rift.mjs's Rift
 * placeholder tiers. Names cross-checked against idleon-toolbox's hole.ts:278-295 `caverns: {}`
 * object key order (theWell, motherlode, theDen, bravery, theBell, theHarp, theLamp, theHive,
 * grotto, justice, theJars, evertree, wisdom, gambit, theTemple, theFountain,
 * theBottomlessTrench, crystalGlunkoCove) — EXACT match, 0 mismatch, 18-for-18.
 *
 * UNLOCK RULE (the entire rule — there is no separate per-cavern resource/item gate):
 *   `"CavernsOwned"==d)return Math.min(18, VillagerLV(0,0))` — N.js:18233, verbatim.
 * i.e. cavern at idx N (in-game "CAVERN_{N+1}") unlocks precisely when the Explorer (villager 0)
 * reaches level N+1; total unlocked account-wide is capped at 18. This is DIRECTLY the flavor
 * text of HolesInfo[20][0] ("Each LV of this villager unlocks a new cavern!") made literal — no
 * hidden per-cavern currency/item requirements exist for unlocking (skilling-cavern *resource
 * sink to find an opal inside*, e.g. Mining/Catching/Choppin'/Fishing Efficiency thresholds in
 * HolesInfo[25], is a DIFFERENT, in-cavern progression mechanic — out of scope here).
 * VERIFIED independently: idleon-toolbox's hole.ts:150 computes the identical
 * `unlockedCaverns = Math.min(18, villagersLevels?.[0])` — 0 mismatch.
 *
 * Per-character CURRENT cavern (which of the unlocked caverns a given character is standing in)
 * is separately tracked at `Holes[0][charIndex]` (0-based; e.g. N.js:5622, 6097, 19709) — this is
 * per-character save state, not a static table, and is out of scope to map here.
 * ------------------------------------------------------------------------------------------ */
export const CAVERNS = [
  { idx: 0, name: "The Well", unlocksAtVillager0Level: 1 },
  { idx: 1, name: "Motherlode", unlocksAtVillager0Level: 2 },
  { idx: 2, name: "The Den", unlocksAtVillager0Level: 3 },
  { idx: 3, name: "Bravery", unlocksAtVillager0Level: 4 },
  { idx: 4, name: "The Bell", unlocksAtVillager0Level: 5 },
  { idx: 5, name: "The Harp", unlocksAtVillager0Level: 6 },
  { idx: 6, name: "The Lamp", unlocksAtVillager0Level: 7 },
  { idx: 7, name: "The Hive", unlocksAtVillager0Level: 8 },
  { idx: 8, name: "Grotto", unlocksAtVillager0Level: 9 },
  { idx: 9, name: "Justice", unlocksAtVillager0Level: 10 },
  { idx: 10, name: "The Jars", unlocksAtVillager0Level: 11 },
  { idx: 11, name: "Evertree", unlocksAtVillager0Level: 12 },
  { idx: 12, name: "Wisdom", unlocksAtVillager0Level: 13 },
  { idx: 13, name: "Gambit", unlocksAtVillager0Level: 14 },
  { idx: 14, name: "The Temple", unlocksAtVillager0Level: 15 },
  { idx: 15, name: "The Fountain", unlocksAtVillager0Level: 16 },
  { idx: 16, name: "The Bottomless Trench", unlocksAtVillager0Level: 17 },
  { idx: 17, name: "Crystal Glunko Cove", unlocksAtVillager0Level: 18 },
  // idx 18-19: literal "BRUH","BRUH" placeholders in HolesInfo[68] — reserved, unbuilt, beyond
  // the CavernsOwned cap of 18; intentionally omitted from this array.
];

/** min(18, villager-0 level) — the exact CavernsOwned expression, N.js:18233. */
export function cavernsOwned(explorerLevel) {
  return Math.min(18, explorerLevel);
}

/* --------------------------------------------------------------------------------------------
 * OUT-OF-SCOPE POINTERS (for a future extraction pass — not extracted in this file):
 *   - Engineer blueprints (~90/107 total, B_UPG ids):  na.HolesBuildings=function(){return[...]}
 *     N.js:23616 (107-entry flat array, [name,type,currencyIdx,cost,repeatFlag,flavor] per row).
 *     Runtime formulas: `"B_UPG"==d` case, N.js:18233-18258 (bespoke per-id, only a handful
 *     ported so far — see bonuses/holes.mjs's bUpg()).
 *   - The Fountain (3 waters x 20 upgrades x marble tiers): `Fountain_BonTOT`/`HoleFountUPG`
 *     accessed throughout `m._customBlock_Holes2` (N.js:18308+); referenced in
 *     bonuses/holes.mjs's monument helpers but its own na.* source table was not located in this
 *     pass (searched `na.HoleFount*=function` — no match; likely nested inside HolesInfo or a
 *     CustomLists.h field set elsewhere — needs a wider search).
 *   - Studies (20, "StudyBolaiaBonuses"/"StudyReqForBolaia"): N.js:18300 area; coefficient table
 *     HolesInfo[70] (N.js:23586).
 *   - Cosmo Majiks (`CosmoUpgrades`, `CosmoBonusQTY`): na.CosmoUpgrades=function(){return[...]}
 *     N.js:23610; runtime `"CosmoBonusQTY"==d`, N.js:18300ish.
 *   - Monuments (Bravery/Justice/Wisdom/Compassion, `MonumentROGbonuses`/`MonumentHRbonuses`):
 *     coefficient table HolesInfo[37] (N.js:23586); partially ported in bonuses/holes.mjs
 *     (WisdomEvo, JusticeArtifact).
 *   - Measurements (11, `MeasurementBonusTOTAL`/`MeasurementQTYfound`): N.js:18245-18254;
 *     currency-index table HolesInfo[50], multiplier-index table HolesInfo[52].
 *   - Lamp wishes (`LampWishes`, `LampBonuses`): na.LampWishes=function(){return[...]} N.js:23606;
 *     partially ported in bonuses/holes.mjs (lampBonus()).
 *   - Gambit (`GambitBonuses`/`GambitPts`): N.js:18313-18319, coefficient table HolesInfo[71].
 * ------------------------------------------------------------------------------------------ */
